org: yadhav
app: safe-settings
service: safe-settings
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  environment:
    APP_ID: ${param:APP_ID}
    PRIVATE_KEY: ${param:PRIVATE_KEY}
    WEBHOOK_SECRET: ${param:WEBHOOK_SECRET}
    NODE_ENV: production
    LOG_LEVEL: debug

functions:
  webhooks:
    handler: handler.webhooks
    events:
      - httpApi:
          path: /api/github/webhooks
          method: post
  cronHandler:
    handler: handler.scheduler
    memorySize: 256
    timeout: 900 # 15 mins (max)
    environment:
      NODE_ENV: production
      LOG_LEVEL: debug
    events:
      - schedule:
          rate: rate(30 minutes)
          enabled: false # set to true to auto-enable
          input: {}
